model_downloader:
  env:
    AZURE_ML_SUBSCRIPTION_ID: 94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a
    AZURE_ML_RESOURCE_GROUP_NAME: diabetes-classifier-2024
    AZURE_ML_WORKSPACE_NAME: diabetes-classifier-2024-dev
    AZURE_TENANT_ID: e6ba44d9-c40a-4dc9-b59f-8fff330da1c0
    AZURE_CLIENT_ID: efc9afe4-877c-4ccb-a264-2a0ee10b8c68
  model:
    model_name: diabetes-classifier-model
    version: 2
  download_params:
    model_download_location: model/